USE [master]
GO
/****** Object:  Database [spring-batch-demo]    Script Date: 6/12/2024 2:55:16 PM ******/
CREATE DATABASE [spring-batch-demo]
 CONTAINMENT = NONE
 ON  PRIMARY
( NAME = N'spring-batch-demo', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\spring-batch-demo.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON
( NAME = N'spring-batch-demo_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\spring-batch-demo_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [spring-batch-demo] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [spring-batch-demo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [spring-batch-demo] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [spring-batch-demo] SET ANSI_NULLS OFF
GO
ALTER DATABASE [spring-batch-demo] SET ANSI_PADDING OFF
GO
ALTER DATABASE [spring-batch-demo] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [spring-batch-demo] SET ARITHABORT OFF
GO
ALTER DATABASE [spring-batch-demo] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [spring-batch-demo] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [spring-batch-demo] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [spring-batch-demo] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [spring-batch-demo] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [spring-batch-demo] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [spring-batch-demo] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [spring-batch-demo] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [spring-batch-demo] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [spring-batch-demo] SET  DISABLE_BROKER
GO
ALTER DATABASE [spring-batch-demo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [spring-batch-demo] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [spring-batch-demo] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [spring-batch-demo] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [spring-batch-demo] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [spring-batch-demo] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [spring-batch-demo] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [spring-batch-demo] SET RECOVERY FULL
GO
ALTER DATABASE [spring-batch-demo] SET  MULTI_USER
GO
ALTER DATABASE [spring-batch-demo] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [spring-batch-demo] SET DB_CHAINING OFF
GO
ALTER DATABASE [spring-batch-demo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO
ALTER DATABASE [spring-batch-demo] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO
ALTER DATABASE [spring-batch-demo] SET DELAYED_DURABILITY = DISABLED
GO
ALTER DATABASE [spring-batch-demo] SET ACCELERATED_DATABASE_RECOVERY = OFF
GO
EXEC sys.sp_db_vardecimal_storage_format N'spring-batch-demo', N'ON'
GO
ALTER DATABASE [spring-batch-demo] SET QUERY_STORE = ON
GO
ALTER DATABASE [spring-batch-demo] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [spring-batch-demo]
GO
USE [spring-batch-demo]
GO
/****** Object:  Sequence [dbo].[BATCH_JOB_EXECUTION_SEQ]    Script Date: 6/12/2024 2:55:16 PM ******/
CREATE SEQUENCE [dbo].[BATCH_JOB_EXECUTION_SEQ]
 AS [bigint]
 START WITH 0
 INCREMENT BY 1
 MINVALUE 0
 MAXVALUE 9223372036854775807
 NO CACHE
GO
USE [spring-batch-demo]
GO
/****** Object:  Sequence [dbo].[BATCH_JOB_SEQ]    Script Date: 6/12/2024 2:55:16 PM ******/
CREATE SEQUENCE [dbo].[BATCH_JOB_SEQ]
 AS [bigint]
 START WITH 0
 INCREMENT BY 1
 MINVALUE 0
 MAXVALUE 9223372036854775807
 NO CACHE
GO
USE [spring-batch-demo]
GO
/****** Object:  Sequence [dbo].[BATCH_STEP_EXECUTION_SEQ]    Script Date: 6/12/2024 2:55:16 PM ******/
CREATE SEQUENCE [dbo].[BATCH_STEP_EXECUTION_SEQ]
 AS [bigint]
 START WITH 0
 INCREMENT BY 1
 MINVALUE 0
 MAXVALUE 9223372036854775807
 NO CACHE
GO
/****** Object:  Table [dbo].[BATCH_JOB_EXECUTION]    Script Date: 6/12/2024 2:55:16 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BATCH_JOB_EXECUTION](
	[JOB_EXECUTION_ID] [bigint] NOT NULL,
	[VERSION] [bigint] NULL,
	[JOB_INSTANCE_ID] [bigint] NOT NULL,
	[CREATE_TIME] [datetime] NOT NULL,
	[START_TIME] [datetime] NULL,
	[END_TIME] [datetime] NULL,
	[STATUS] [varchar](10) NULL,
	[EXIT_CODE] [varchar](2500) NULL,
	[EXIT_MESSAGE] [varchar](2500) NULL,
	[LAST_UPDATED] [datetime] NULL,
PRIMARY KEY CLUSTERED
(
	[JOB_EXECUTION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BATCH_JOB_EXECUTION_CONTEXT]    Script Date: 6/12/2024 2:55:16 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BATCH_JOB_EXECUTION_CONTEXT](
	[JOB_EXECUTION_ID] [bigint] NOT NULL,
	[SHORT_CONTEXT] [varchar](2500) NOT NULL,
	[SERIALIZED_CONTEXT] [varchar](max) NULL,
PRIMARY KEY CLUSTERED
(
	[JOB_EXECUTION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BATCH_JOB_EXECUTION_PARAMS]    Script Date: 6/12/2024 2:55:16 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BATCH_JOB_EXECUTION_PARAMS](
	[JOB_EXECUTION_ID] [bigint] NOT NULL,
	[PARAMETER_NAME] [varchar](100) NOT NULL,
	[PARAMETER_TYPE] [varchar](100) NOT NULL,
	[PARAMETER_VALUE] [varchar](2500) NULL,
	[IDENTIFYING] [char](1) NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BATCH_JOB_INSTANCE]    Script Date: 6/12/2024 2:55:16 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BATCH_JOB_INSTANCE](
	[JOB_INSTANCE_ID] [bigint] NOT NULL,
	[VERSION] [bigint] NULL,
	[JOB_NAME] [varchar](100) NOT NULL,
	[JOB_KEY] [varchar](32) NOT NULL,
PRIMARY KEY CLUSTERED
(
	[JOB_INSTANCE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [JOB_INST_UN] UNIQUE NONCLUSTERED
(
	[JOB_NAME] ASC,
	[JOB_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BATCH_STEP_EXECUTION]    Script Date: 6/12/2024 2:55:16 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BATCH_STEP_EXECUTION](
	[STEP_EXECUTION_ID] [bigint] NOT NULL,
	[VERSION] [bigint] NOT NULL,
	[STEP_NAME] [varchar](100) NOT NULL,
	[JOB_EXECUTION_ID] [bigint] NOT NULL,
	[CREATE_TIME] [datetime] NOT NULL,
	[START_TIME] [datetime] NULL,
	[END_TIME] [datetime] NULL,
	[STATUS] [varchar](10) NULL,
	[COMMIT_COUNT] [bigint] NULL,
	[READ_COUNT] [bigint] NULL,
	[FILTER_COUNT] [bigint] NULL,
	[WRITE_COUNT] [bigint] NULL,
	[READ_SKIP_COUNT] [bigint] NULL,
	[WRITE_SKIP_COUNT] [bigint] NULL,
	[PROCESS_SKIP_COUNT] [bigint] NULL,
	[ROLLBACK_COUNT] [bigint] NULL,
	[EXIT_CODE] [varchar](2500) NULL,
	[EXIT_MESSAGE] [varchar](2500) NULL,
	[LAST_UPDATED] [datetime] NULL,
PRIMARY KEY CLUSTERED
(
	[STEP_EXECUTION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BATCH_STEP_EXECUTION_CONTEXT]    Script Date: 6/12/2024 2:55:16 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BATCH_STEP_EXECUTION_CONTEXT](
	[STEP_EXECUTION_ID] [bigint] NOT NULL,
	[SHORT_CONTEXT] [varchar](2500) NOT NULL,
	[SERIALIZED_CONTEXT] [varchar](max) NULL,
PRIMARY KEY CLUSTERED
(
	[STEP_EXECUTION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[table1]    Script Date: 6/12/2024 2:55:16 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[table1](
	[id] [bigint] NOT NULL,
	[data] [varchar](255) NULL,
	[expiry_date] [datetime2](6) NULL,
	[status] [varchar](255) NULL,
PRIMARY KEY CLUSTERED
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[table2]    Script Date: 6/12/2024 2:55:16 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[table2](
	[id] [bigint] NOT NULL,
	[data] [varchar](255) NULL,
	[deleted] [bit] NOT NULL,
	[table1id] [bigint] NULL,
PRIMARY KEY CLUSTERED
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BATCH_JOB_EXECUTION] ADD  DEFAULT (NULL) FOR [START_TIME]
GO
ALTER TABLE [dbo].[BATCH_JOB_EXECUTION] ADD  DEFAULT (NULL) FOR [END_TIME]
GO
ALTER TABLE [dbo].[BATCH_STEP_EXECUTION] ADD  DEFAULT (NULL) FOR [START_TIME]
GO
ALTER TABLE [dbo].[BATCH_STEP_EXECUTION] ADD  DEFAULT (NULL) FOR [END_TIME]
GO
ALTER TABLE [dbo].[BATCH_JOB_EXECUTION]  WITH CHECK ADD  CONSTRAINT [JOB_INST_EXEC_FK] FOREIGN KEY([JOB_INSTANCE_ID])
REFERENCES [dbo].[BATCH_JOB_INSTANCE] ([JOB_INSTANCE_ID])
GO
ALTER TABLE [dbo].[BATCH_JOB_EXECUTION] CHECK CONSTRAINT [JOB_INST_EXEC_FK]
GO
ALTER TABLE [dbo].[BATCH_JOB_EXECUTION_CONTEXT]  WITH CHECK ADD  CONSTRAINT [JOB_EXEC_CTX_FK] FOREIGN KEY([JOB_EXECUTION_ID])
REFERENCES [dbo].[BATCH_JOB_EXECUTION] ([JOB_EXECUTION_ID])
GO
ALTER TABLE [dbo].[BATCH_JOB_EXECUTION_CONTEXT] CHECK CONSTRAINT [JOB_EXEC_CTX_FK]
GO
ALTER TABLE [dbo].[BATCH_JOB_EXECUTION_PARAMS]  WITH CHECK ADD  CONSTRAINT [JOB_EXEC_PARAMS_FK] FOREIGN KEY([JOB_EXECUTION_ID])
REFERENCES [dbo].[BATCH_JOB_EXECUTION] ([JOB_EXECUTION_ID])
GO
ALTER TABLE [dbo].[BATCH_JOB_EXECUTION_PARAMS] CHECK CONSTRAINT [JOB_EXEC_PARAMS_FK]
GO
ALTER TABLE [dbo].[BATCH_STEP_EXECUTION]  WITH CHECK ADD  CONSTRAINT [JOB_EXEC_STEP_FK] FOREIGN KEY([JOB_EXECUTION_ID])
REFERENCES [dbo].[BATCH_JOB_EXECUTION] ([JOB_EXECUTION_ID])
GO
ALTER TABLE [dbo].[BATCH_STEP_EXECUTION] CHECK CONSTRAINT [JOB_EXEC_STEP_FK]
GO
ALTER TABLE [dbo].[BATCH_STEP_EXECUTION_CONTEXT]  WITH CHECK ADD  CONSTRAINT [STEP_EXEC_CTX_FK] FOREIGN KEY([STEP_EXECUTION_ID])
REFERENCES [dbo].[BATCH_STEP_EXECUTION] ([STEP_EXECUTION_ID])
GO
ALTER TABLE [dbo].[BATCH_STEP_EXECUTION_CONTEXT] CHECK CONSTRAINT [STEP_EXEC_CTX_FK]
GO
USE [master]
GO
ALTER DATABASE [spring-batch-demo] SET  READ_WRITE
GO
